[env:esp32-s3-devkitc-1]
platform = espressif32
; 注意：DNESP32S3 通常采用 N16R8 配置（16MB Flash + 8MB PSRAM）
board = esp32-s3-devkitc-1
framework = arduino ; 或者 espidf
monitor_speed = 115200

; 针对 N16R8 模组的 Flash 和 PSRAM 开启配置
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
board_build.arduino.memory_type = qio_opi ; 对应 16MB Flash 和 8MB Octal PSRAM
board_build.flash_mode = qio
board_build.f_flash = 80000000L