#pragma once

#include <driver/gpio.h>
#include <driver/i2c_master.h>
#include <driver/i2s_std.h>
#include <driver/spi_master.h>
#include <esp_io_expander.h>

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define POWER_BUTTON_GPIO GPIO_NUM_6
#define POWER_HOLD_GPIO GPIO_NUM_7
#define BATTERY_ADC_GPIO GPIO_NUM_8
#define RTC_INTERRUPT_GPIO GPIO_NUM_9

#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_2
#define AUDIO_I2S_MIC_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_39
#define AUDIO_I2S_MIC_SLOT I2S_STD_SLOT_RIGHT

#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_47
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_48
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_38
#define AUDIO_I2S_SPK_SLOT I2S_STD_SLOT_LEFT

#define BOARD_I2C_PORT I2C_NUM_0
#define BOARD_I2C_SCL_GPIO GPIO_NUM_10
#define BOARD_I2C_SDA_GPIO GPIO_NUM_11
#define BOARD_I2C_CLOCK_HZ 400000

#define TCA9554_I2C_ADDRESS 0x20
#define RTC_I2C_ADDRESS 0x51
#define TOUCH_I2C_ADDRESS 0x53
#define IMU_I2C_ADDRESS_LOW 0x6A
#define IMU_I2C_ADDRESS_HIGH 0x6B

// The official schematic numbers EXIO1/EXIO2 from one; the component masks
// number the same physical pins from zero.
#define TOUCH_RESET_EXPANDER_PIN IO_EXPANDER_PIN_NUM_0
#define DISPLAY_RESET_EXPANDER_PIN IO_EXPANDER_PIN_NUM_1
#define IMU_INTERRUPT_2_EXPANDER_PIN IO_EXPANDER_PIN_NUM_3
#define IMU_INTERRUPT_1_EXPANDER_PIN IO_EXPANDER_PIN_NUM_4

#define DISPLAY_WIDTH 412
#define DISPLAY_HEIGHT 412
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_BITS_PER_PIXEL 16

#define DISPLAY_SPI_HOST SPI2_HOST
#define DISPLAY_SPI_CLOCK_HZ (40 * 1000 * 1000)
#define DISPLAY_SPI_MODE 3
#define DISPLAY_SPI_CS_GPIO GPIO_NUM_21
#define DISPLAY_SPI_SCLK_GPIO GPIO_NUM_40
#define DISPLAY_SPI_DATA0_GPIO GPIO_NUM_46
#define DISPLAY_SPI_DATA1_GPIO GPIO_NUM_45
#define DISPLAY_SPI_DATA2_GPIO GPIO_NUM_42
#define DISPLAY_SPI_DATA3_GPIO GPIO_NUM_41
#define DISPLAY_BACKLIGHT_GPIO GPIO_NUM_5
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define TOUCH_INTERRUPT_GPIO GPIO_NUM_4
#define TOUCH_MAX_POINTS 5
